### ISSUE TITLE
Figma design for Login page

### ISSUE THREAD

**Issue by ninalamo** [BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1#1]
## Acceptance criteria:
* Should have Username, Password and a button "LOGIN"
* Should have link to register "don't have account?" 
* Make it creative and simple

## UI requirements:

- [ ] - USERNAME
- [ ] - PASSWORD
- [ ] - REGISTER button link
- [ ] - FORGOT password button link

## **Done**
Send a Screenshot in the comment section.

**Comment by AndoJoshuaBSIT32E1** [comment]
Figma design for login

**Comment by FugenAira-BSIT32E1** [comment]
![Screenshot 2024-05-12 124926](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/153443814/0ced21e0-b28a-4a98-8f99-0cccd77ebdc8)

**Comment by AndoJoshuaBSIT32E1** [comment]
Pasend nga ng link po nung figma

**Comment by FugenAira-BSIT32E1** [comment]
https://www.figma.com/design/T55LjQWOwTNO2hqTq02BBk/LOGIN-DESIGN1?node-id=0-1&t=trBktYgiPerGj9qF-0

**Comment by AndoJoshuaBSIT32E1** [comment]
Thank you po

**Comment by FugenAira-BSIT32E1** [comment]
![Screenshot 2024-05-25 184429](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/153443814/976e58c1-00ae-4b54-83bb-56b7ceba9f34)

**Comment by FugenAira-BSIT32E1** [comment]
https://www.figma.com/design/T55LjQWOwTNO2hqTq02BBk/LOGIN-DESIGN1?node-id=0-1&t=LchwUF5nmrzehDvQ-0
