### ISSUE TITLE
Figma design for Register page

### ISSUE THREAD

**Issue by AndoJoshuaBSIT32E1** [BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1#4]
## Acceptance criteria:

1. Should have Lastname, First name, Username, Password and a button "Register"
2. Should have link to login "Already have account?" button link
3. Make it creative and simple

## UI requirements:

- [ ] -Last name
- [ ] -First name
- [ ] - USERNAME
- [ ] - PASSWORD
- [ ] - Login button link

## Done:
Send a Screenshot in the comment section.

**Comment by BandeMeliza-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/155070275/92d7dec5-8cb0-4804-89d2-adcbe1fa2b30)

**Comment by BandeMeliza-BSIT32E1** [comment]
https://www.figma.com/design/WcctmcYEaITXpIvSGmkRlK/Registration?m=dev&node-id=0%3A1&t=TrDuwlw03DeCjd7P-1

UI Link

**Comment by ninalamo** [comment]
Add Confirm Password field

**Comment by BandeMeliza-BSIT32E1** [comment]
![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/155070275/537a8338-d0b5-4d87-933f-9a2caa53f112)

**Comment by AndoJoshuaBSIT32E1** [comment]
pabago ako nung color pallete mo sa register po na may similarities don sa login then send mo here Thank you

**Comment by BandeMeliza-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/155070275/7f5ab2cb-fa76-4144-8d5d-7fe6b49302f9)

**Comment by BandeMeliza-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/155070275/e88fb1b5-b15b-4f3c-8370-093d19ef9e53)

**Comment by BandeMeliza-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/155070275/f01cd4ff-9248-4cc1-9607-a44c5ca037e9)
