### ISSUE TITLE
Figma Design for Adviser page

### ISSUE THREAD

**Issue by AndoJoshuaBSIT32E1** [BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1#44]
## Acceptance Criteria
1. must have the list of the subjects to input the grades (e.g. ENGLISH, SCIENCE, MATH...)
2. must have input fields to enter the name of the students 
3. I should be able to see a suggestions each strand below  

## UI Requirement

- [ ] LIST OF SUBJECTS
- [ ] NAME OF THE STUDENT
- [ ] SUGGESTION OF EACH STRAND TO BE TAKEN

## DONE
Send a screenshot in the comment section

**Comment by AndoJoshuaBSIT32E1** [comment]
pasend po ako here nung link po sa figma and ss niyo po kasi naipasa niyo dun sa lumang inaassign ko po sainyo. thank you

**Comment by Villareal-AubreyMae-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160814647/0c730bb7-bee4-4cd6-90c4-6abf28772ee4)

[https://www.figma.com/design/VEOedciZHsfx0RBVTiTppx/Form-Page?node-id=0%3A1&t=jm4vPIZoJDqujfjH-1](url)

**Comment by Villareal-AubreyMae-BSIT32E1** [comment]
![Adviser Module](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160814647/df03b0ec-209e-42e8-931e-9fcde37b6103)
![DashBoard](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160814647/33111440-9618-40ae-b6d6-01d66f02a55f)
![Form Page](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160814647/b4c74747-f0da-4a38-9a2e-f92c87f7bfcc)
![Students](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160814647/4a5b365e-dc5d-40ba-902d-6b1cb608abe6)

[https://www.figma.com/design/VEOedciZHsfx0RBVTiTppx/Form-Page?node-id=0-1&t=sEIEX1I2ri0Nb9sL-1](url)

**Comment by AndoJoshuaBSIT32E1** [comment]
### Hind ko maopen ang link mo sa figma yung figma link ang isend 


![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160818162/d1ca9d56-b789-4fdc-aa99-cea8c21022bd)

**Comment by Villareal-AubreyMae-BSIT32E1** [comment]
https://www.figma.com/design/VEOedciZHsfx0RBVTiTppx/Form-Page?node-id=0-1&t=W1SJ50UsqaiWwNyM-1
