### ISSUE TITLE
Figma design for profile

### ISSUE THREAD

**Issue by AndoJoshuaBSIT32E1** [BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1#45]
## Acceptance Criteria
1. Must have a name of the user
2. Should display the result after entering the grades together with suggestions strand to take
3. be creative in designing

## UI Requirements

- [ ] Name
- [ ] Grades
- [ ] Result suggestions

## DONE
Send Screenshot in the comment section

**Comment by Mance-Rizzalyn-BSIT32E1** [comment]
https://www.figma.com/design/3HoesqECUl6yTFec9CJatV/Profile?node-id=0%3A1&t=iNHsOxB1dJrn2Phu-1

**Comment by Mance-Rizzalyn-BSIT32E1** [comment]
![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/148579766/85786c27-d291-4bbf-a06d-f27b6ebd99f1)

**Comment by AndoJoshuaBSIT32E1** [comment]
> ![image](https://private-user-images.githubusercontent.com/148579766/331082987-85786c27-d291-4bbf-a06d-f27b6ebd99f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTIzMTcsIm5iZiI6MTcxNjIxMjAxNywicGF0aCI6Ii8xNDg1Nzk3NjYvMzMxMDgyOTg3LTg1Nzg2YzI3LWQyOTEtNGJiZi1hMDZkLWYyN2I2ZWJkOTlmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMzMzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDA2OWYwMDk1OGViMmU2Mzc0MmI3Mjk4Y2JkNWVjZDZhZWZkNTllNzMzNmExOGFkMGQ2MWJmNjM1NzUyNTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.95f2l3GG6-mfaqPiLJiSUi1u63YAS40QfBDA_AcaIBU)

Yung sa grades daw mance gawin mo raw naka Table or yung parang nasa report card siya ganun

**Comment by Mance-Rizzalyn-BSIT32E1** [comment]
https://www.figma.com/design/hB5FZDHyK5f2dbmQYOWHDQ/Profile1?node-id=0%3A1&t=oebAFTfIxwMm8dHs-1

![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/148579766/438feb74-37a1-47fc-ab32-b19ca8420bfc)

**Comment by Mance-Rizzalyn-BSIT32E1** [comment]
https://www.figma.com/design/3HoesqECUl6yTFec9CJatV/Profile?node-id=0%3A1&t=nOptWCeMPiqPESxf-1

![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/148579766/f720b99a-9172-4f78-93c4-4734f00f3d45)

**Comment by AndoJoshuaBSIT32E1** [comment]
### Patanggal ako nito
![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160818162/73131764-a70d-4b2f-8c06-f6e6dcb60327)
### Tapos yung user icon mo dun sa taas pabago ako gawin mo ganito
![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160818162/69464ae2-bf1f-4315-99cc-78cf81622b44)
### Then tanggalin mo yung student name ilipat mo dyan yung Grade 10, tas lagyan mo ng Section name e.g Nazareth
![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160818162/c6cb9fca-ee2e-4c00-98e4-4c30a0e43236)
### tas palagay ako kung san diyan yung major like e.g Primary and secondary recommendation para maidentify kaagad
![image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/160818162/9b05f174-be0d-48f8-a574-d266c31ba31a)

**Comment by Mance-Rizzalyn-BSIT32E1** [comment]
https://www.figma.com/design/hB5FZDHyK5f2dbmQYOWHDQ/Profile1?node-id=0-1&t=LAuxfMIZpaI3O3sf-1



![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/148579766/71ae40a0-28bc-4296-a817-72ad9529d7cf)

**Comment by Mance-Rizzalyn-BSIT32E1** [comment]
https://www.figma.com/design/h6uj5Nd8MbNFV6l06W5En4/Profile?node-id=0-1&t=NVv2QSMNvvx9WiJQ-1



![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/148579766/43124337-53ca-4e7a-a636-b37c47079606)

**Comment by AndoJoshuaBSIT32E1** [comment]
Thank you
