### ISSUE TITLE
Figma design for Home page

### ISSUE THREAD

**Issue by AndoJoshuaBSIT32E1** [BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1#5]
## **Acceptance criteria:**
1. should have navigation including: HOME and PROFILE
2. I should be able at HOME PAGE the introducing of each Strand following the descriptions and Course that could be taken under the strand 

## **UI Requirement:**

- [ ] Home
- [ ] All Strand Introducing and descriptions
- [ ] Course and Jobs applicable to each strand

## Done
Send a Screenshot in the comment section

**Comment by Go-MaryKierine-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/146524749/97cb3a4b-0f9b-4b59-a22a-b7da17478853)

**Comment by Go-MaryKierine-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/146524749/ed7c491f-f69e-494e-b21c-ec6fccd43dfe)
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/146524749/539a1513-5d86-4ba4-b2ec-04b2c62b84d1)
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/146524749/df975ac7-28dd-4c89-af2f-1da3a93e9a54)

FULL SCREEN

**Comment by AndoJoshuaBSIT32E1** [comment]
Thank you po

**Comment by Go-MaryKierine-BSIT32E1** [comment]
https://www.figma.com/design/PWo2Cy0EFqNEvCWnuO8YXm/HOME-PAGE?m=auto&t=shbLRCO5NWwcInnv-6

**Comment by Go-MaryKierine-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/146524749/6e20cdb6-c875-49f8-998b-864ebdf0f1f1)

UPDATED HOME PAGE

**Comment by Go-MaryKierine-BSIT32E1** [comment]
![Image](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/assets/146524749/8a6bcdc0-13a1-47e0-aec0-73527a803263)
